# Generated by Django 6.0.4 on 2026-05-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="blog/", verbose_name="Изображение")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication_attribute", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("views", models.IntegerField(default=0, verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["-created_at"],
            },
        ),
    ]
